sudo: required
services:
  - docker

before_install:
  - docker build -t alexanderspevak/react-test -f ./client/Dockefile.dev  ./client

script:
  - docker run alexanderspevak/react-test npm test -- --coverage

after_success:
  - docker build -t alexanderspevak/multi-client ./client
  - docker build -t alexanderspevak/multi-nginx ./nginx
  - docker build -t alexanderspevak/multi-server ./server
  - docker build -t alexanderspevak/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push alexanderspevak/multi-client
  - docker push alexanderspevak/multi-nginx
  - docker push alexanderspevak/multi-server
  - docker push alexanderspevak/multi-worker